import Blogs from "@/components/blogs/Blogs";
import { getAll } from "@/services/blogs";
import { useSession } from "next-auth/react";
import Head from "next/head";

export default function Dashboard({ blogs }) {
  const session = useSession();

  return (
    <main>
      <Head>
        <title>Personal Blogging App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      {session.status === "authenticated" && (
      <section class="text-gray-600 body-font relative">
        <div class="container px-5 py-24 mx-auto">
          <form class="lg:w-1/2 md:w-2/3 mx-auto" onSubmit={(e) => {
            e.preventDefault();
          }}>
            <div class="flex flex-wrap -m-2">
              <div class="p-2 w-full">
                <h1>Dashboard</h1>
                <div class="relative">
                  <label for="message" class="leading-7 text-sm text-gray-600">Title</label>
                  <input type="text" id="title" name="title" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" />
                </div>
                <div class="relative">
                  <label for="message" class="leading-7 text-sm text-gray-600">Blog</label>
                  <textarea id="message" name="message" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
                </div>
              </div>
              <div class="p-2 w-full">
                <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </section>
      )}
      <section className="text-gray-600 body-font overflow-hidden margin b-radius">
        <div className="container px-5 py-24 mx-auto">
          <div className="-my-8 divide-y-2 divide-gray-100">
            {blogs.map((blog) => (
              <Blogs
                blog={blog}
                key={blog.id}
                canDelete={
                  session.status === "authenticated" &&
                  session.data.user.email === blog.userEmail
                }
              />
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}

export async function getServerSideProps({ req }) {
  const data = getAll();

  return {
    props: {
      blogs: data,
    },
  };
}
