import Blogs from "@/components/blogs/Blogs";
import { getAll } from "@/services/blogs";
import { useSession } from "next-auth/react";
import Head from "next/head";

export default function Dashboard({ blogs }) {
  const session = useSession();

  return (
    <main>
      <Head>
        <title>Personal Blogging App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <section className="text-gray-600 body-font overflow-hidden marginTB b-radius">
        <div className="container px-5 py-24 mx-auto">
          {session.status === "authenticated" && (
            <div className="">
              logged in
            </div>
          )}
          <div className="-my-8 divide-y-2 divide-gray-100">
            {blogs.map((blog) => (
              <Blogs
                blog={blog}
                key={blog.id}
                canDelete={
                  session.status === "authenticated" &&
                  session.data.user.email === blog.userEmail
                }
              />
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}

export async function getServerSideProps({ req }) {
  const data = getAll();

  return {
    props: {
      blogs: data,
    },
  };
}
