import Image from 'next/image';
import Head from 'next/head';
import Blogs from '@/components/blogs/Blogs';
import Link from 'next/link';
import { getByUserEmail } from '@/services/blogs';
import { useRouter } from 'next/router';

export default function Home({ blogs }) {
  const router = useRouter;
  const email = router.query;
  return (
    <main>
      <Head>
        <title>Personal Blogging App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <section className="text-gray-600 body-font overflow-hidden marginTB b-radius">
        <Link href="/">
          Go back to dashboard
        </Link>
        <div className="container px-5 py-24 mx-auto">
          <h1 className='text-violet-800'> All Blogs</h1>
          <div className="-my-8 divide-y-2 divide-gray-100">
            {blogs.map((blog) => (
              <Blogs blog={blog} key={blog.id} />
            ))}
          </div>
        </div>
      </section >
    </main>
  );
}

export async function getServerSideProps({ req, query }) {
  const user_email = query.email;
  const data = getByUserEmail(user_email);

  return {
    props: { blogs: data },
  };
}
